swagger: "2.0"
info: 
  title: API de Ordens
  description: Documentação da API de ordens do microsserviço order-management-order
  version: 1.0.0

host: localhost
schemes:  
  - http
tags: 
  - name: Orders
    description: API de ordens

paths:
  /orders:
    post:
      tags: 
        - Orders
      summary: Endpoint de criação de ordem
      produces: 
        - application/json
      consumes:
        - application/json
      parameters:
        - name: body
          required: true
          in: body
          schema: 
            $ref: "#/definitions/CreateOrderRequestDto"
      responses: 
        201:
          description: Ordem criada com sucesso
          schema:
            $ref: "#/definitions/OrderResponseDto"

definitions:
  OrderResponseDto:
    type: object
    properties: 
      id: 
        type: integer
        description: Identificador da ordem
        example: 12345
      createdAt: 
        type: string
        description: Data de criação da ordem
        example: '2024-11-01T19:35:41.00'
      amount: 
        type: number
        description: Valor total da ordem
        example: 250.25
  CreateOrderRequestDto:
    type: object
    required: 
     - name
     - cpf
    properties:
      name:
        type: string
        description: Nome do cliente
        example: John Doe I
      cpf:
        type: string
        description: CPF do cliente
        example: '12345678901'



    # private BigDecimal amount;

    # private OrderStatusEnum status;

    # private String name;

    # private String cpf;

    # private String address;

    # private String postalCode;

    # private String city;

    # private String state;

    # private LocalDateTime attemptedPaymentAt;

    # private List<OrderItemDto> items;